name = "Ark"
uuid = "56664e29-41e4-4ea5-ab0e-825499acc647"
version = "0.1.0"
authors = [
    "Martin Lange <martin_lange_@gmx.net>",
    "Adriano Meligrana <adriano.meligrana@centai.eu>",
]

[deps]
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
FunctionWrappers = "1"
StaticArrays = "1"
julia = "1.12"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
