name = "Ark"
uuid = "56664e29-41e4-4ea5-ab0e-825499acc647"
version = "0.1.0-dev"
authors = ["Martin Lange <martin_lange_@gmx.net>"]

[deps]

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[targets]
test = ["Test", "Revise"]
