[deps]
Ark = "56664e29-41e4-4ea5-ab0e-825499acc647"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
