[deps]
Ark = "56664e29-41e4-4ea5-ab0e-825499acc647"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MiniFB = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
