[deps]
Ark = "56664e29-41e4-4ea5-ab0e-825499acc647"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
MiniFB = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
