[deps]
Ark = "56664e29-41e4-4ea5-ab0e-825499acc647"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MiniFB = "cc649173-1898-4bb8-8a16-ca5f88bd87d9"
