name: Tests (interop)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests (interop)
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
          - '1'
    steps:
      - name: Cancel ongoing test runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Julia
        uses: ./.github/actions/setup-julia
        with:
          julia-version: ${{ matrix.version }}
          project-file: './Project.toml'
      - name: Run tests
        run: julia --project=. run_tests.jl --interop
      - uses: julia-actions/julia-processcoverage@v1
      - name: Archive coverage artifacts
        if: matrix.version == '1'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-interop-${{ matrix.version }}
          path: lcov.info
          if-no-files-found: ignore
      - name: Download all coverage artifacts
        if: matrix.version == '1'
        uses: actions/download-artifact@v4
        with:
          path: coverage_artifacts
      - name: Upload coverage to Codecov
        if: matrix.version == '1'
        uses: codecov/codecov-action@v5
        with:
          directory: coverage_artifacts
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true