name: Tests (demos)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests (large world)
    runs-on: ubuntu-latest
    permissions: # required for caching
      actions: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - name: Set up Julia
      uses: ./.github/actions/setup-julia
      with:
        julia-version: 1
        project-file: './demos/Project.toml'
    - name: Run tests
      run: |
        cd demos
        julia --color=yes --project=. -e 'using Pkg; Pkg.develop(path=".."); Pkg.instantiate()'
        DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --color=yes --project=. logo/main.jl
